// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: everlast/cpc/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// deploy_erc20_native defines if the module should deploy the ERC20 contract for native coin.
	// The denom of the native coin is the same as staking denom.
	DeployErc20Native bool `protobuf:"varint,2,opt,name=deploy_erc20_native,json=deployErc20Native,proto3" json:"deploy_erc20_native,omitempty"`
	// deploy_staking_contract defines if the module should deploy the staking contract.
	DeployStakingContract bool `protobuf:"varint,3,opt,name=deploy_staking_contract,json=deployStakingContract,proto3" json:"deploy_staking_contract,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eabce093aaa4a14, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDeployErc20Native() bool {
	if m != nil {
		return m.DeployErc20Native
	}
	return false
}

func (m *GenesisState) GetDeployStakingContract() bool {
	if m != nil {
		return m.DeployStakingContract
	}
	return false
}

// Params defines the cpc module params
type Params struct {
	// protocol_version is the protocol version of the cpc module
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// whitelisted_deployers is the address of the accounts permitted to deploy the Custom Precompiled Contracts
	WhitelistedDeployers []string `protobuf:"bytes,2,rep,name=whitelisted_deployers,json=whitelistedDeployers,proto3" json:"whitelisted_deployers,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eabce093aaa4a14, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *Params) GetWhitelistedDeployers() []string {
	if m != nil {
		return m.WhitelistedDeployers
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "everlast.cpc.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "everlast.cpc.v1.Params")
}

func init() { proto.RegisterFile("everlast/cpc/v1/genesis.proto", fileDescriptor_8eabce093aaa4a14) }

var fileDescriptor_8eabce093aaa4a14 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd1, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0x07, 0xf0, 0x15, 0x0c, 0xd1, 0xaa, 0x41, 0x27, 0x84, 0xc5, 0xc4, 0x49, 0xb8, 0x88, 0x97,
	0x4e, 0x20, 0x7a, 0x17, 0x25, 0xde, 0x8c, 0x19, 0x89, 0x07, 0x2f, 0x4b, 0x29, 0x2f, 0xa3, 0x71,
	0xac, 0x4b, 0x5b, 0xa7, 0x7c, 0x0b, 0xbf, 0x88, 0xdf, 0x83, 0x23, 0x47, 0x4f, 0xc6, 0xc0, 0x17,
	0x31, 0xb4, 0xcc, 0x18, 0x6f, 0xcb, 0xfb, 0xfd, 0xdf, 0xdb, 0x6b, 0x1e, 0x3e, 0x81, 0x1c, 0x64,
	0x42, 0x95, 0x0e, 0x58, 0xc6, 0x82, 0xbc, 0x13, 0xc4, 0x90, 0x82, 0xe2, 0x8a, 0x64, 0x52, 0x68,
	0xe1, 0x56, 0x0b, 0x26, 0x2c, 0x63, 0x24, 0xef, 0x1c, 0xd7, 0x62, 0x11, 0x0b, 0x63, 0xc1, 0xfa,
	0xcb, 0xc6, 0x5a, 0x1f, 0x08, 0xef, 0xdd, 0xd9, 0xc6, 0xa1, 0xa6, 0x1a, 0xdc, 0x4b, 0x5c, 0xc9,
	0xa8, 0xa4, 0x53, 0xe5, 0xa1, 0x26, 0x6a, 0xef, 0x76, 0x1b, 0xe4, 0xdf, 0x20, 0xf2, 0x60, 0xb8,
	0xbf, 0x35, 0xff, 0x3a, 0x75, 0xc2, 0x4d, 0xd8, 0x25, 0xf8, 0x68, 0x0c, 0x59, 0x22, 0x66, 0x11,
	0x48, 0xd6, 0xbd, 0x88, 0x52, 0xaa, 0x79, 0x0e, 0x5e, 0xa9, 0x89, 0xda, 0xdb, 0xe1, 0xa1, 0xa5,
	0xc1, 0x5a, 0xee, 0x0d, 0xb8, 0x57, 0xb8, 0xb1, 0xc9, 0x2b, 0x4d, 0x9f, 0x79, 0x1a, 0x47, 0x4c,
	0xa4, 0x5a, 0x52, 0xa6, 0xbd, 0xb2, 0xe9, 0xa9, 0x5b, 0x1e, 0x5a, 0xbd, 0xd9, 0x60, 0x6b, 0x82,
	0x2b, 0xf6, 0xff, 0xee, 0x39, 0x3e, 0x30, 0x4f, 0x60, 0x22, 0x89, 0x72, 0x90, 0x8a, 0x8b, 0xd4,
	0xac, 0xbc, 0x1f, 0x56, 0x8b, 0xfa, 0xa3, 0x2d, 0xbb, 0x3d, 0x5c, 0x7f, 0x9d, 0x70, 0x0d, 0x09,
	0x57, 0x1a, 0xc6, 0x91, 0x9d, 0x0c, 0x52, 0x79, 0xa5, 0x66, 0xb9, 0xbd, 0x13, 0xd6, 0xfe, 0xe0,
	0x6d, 0x61, 0xfd, 0xeb, 0xf9, 0xd2, 0x47, 0x8b, 0xa5, 0x8f, 0xbe, 0x97, 0x3e, 0x7a, 0x5f, 0xf9,
	0xce, 0x62, 0xe5, 0x3b, 0x9f, 0x2b, 0xdf, 0x79, 0x3a, 0x8b, 0xb9, 0x9e, 0xbc, 0x8c, 0x08, 0x13,
	0xd3, 0x60, 0xa0, 0x18, 0x4d, 0xfb, 0x83, 0xe0, 0xf7, 0x18, 0x6f, 0xe6, 0x1c, 0x7a, 0x96, 0x81,
	0x1a, 0x55, 0xcc, 0x22, 0xbd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xa8, 0x32, 0xf6, 0xab,
	0x01, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DeployStakingContract {
		i--
		if m.DeployStakingContract {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.DeployErc20Native {
		i--
		if m.DeployErc20Native {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhitelistedDeployers) > 0 {
		for iNdEx := len(m.WhitelistedDeployers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedDeployers[iNdEx])
			copy(dAtA[i:], m.WhitelistedDeployers[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.WhitelistedDeployers[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.ProtocolVersion != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ProtocolVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.DeployErc20Native {
		n += 2
	}
	if m.DeployStakingContract {
		n += 2
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProtocolVersion != 0 {
		n += 1 + sovGenesis(uint64(m.ProtocolVersion))
	}
	if len(m.WhitelistedDeployers) > 0 {
		for _, s := range m.WhitelistedDeployers {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeployErc20Native", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DeployErc20Native = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeployStakingContract", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DeployStakingContract = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolVersion", wireType)
			}
			m.ProtocolVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProtocolVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedDeployers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedDeployers = append(m.WhitelistedDeployers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
